[package]
name = "vegafusion-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vegafusion-core = {path = "../vegafusion-core"}
regex = "^1.5.4"
lazy_static = "^1.4.0"

