[package]
name = "vegafusion-datafusion-udfs"
license = "BSD-3-Clause"
version = "1.1.0"
edition = "2021"
description = "Custom DataFusion UDFs used by VegaFusion"

[dependencies]
ordered-float = "3.4.0"
lazy_static = "^1.4.0"
chrono = "0.4.23"
chrono-tz = "0.8.1"
regex = "^1.5.5"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.1.0"

[dependencies.datafusion-physical-expr]
version = "18.0.0"
