[package]
name = "vegafusion-python-embed"
version = "0.4.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
name = "vegafusion_embed"
crate-type = [ "cdylib",]

[dependencies.serde]
version = "1.0.137"
features = [ "derive",]

[dependencies.serde_json]
version = "1.0.79"

[dependencies.vegafusion-core]
path = "../vegafusion-core"
features = [ "pyo3",]

[dependencies.vegafusion-rt-datafusion]
path = "../vegafusion-rt-datafusion"
features = ["pyarrow"]

[dependencies.tokio]
version = "1.18.1"
features = [ "macros", "rt-multi-thread",]

[dependencies.pyo3]
version = "0.16.4"
features = [ "extension-module",]

[dependencies.mimalloc]
version = "*"
default-features = false
