name: vegafusion_jupyter_dev
channels:
  - conda-forge
dependencies:
  - python =3.7
  - nodejs
  - yarn
  - maturin
  - jupyterlab
  - jupyter-packaging
  - conda-lock
  - pip
  - jupytext
  - python-chromedriver-binary =98
  - pytest >=4.6
  - pytest-cov
  - vega_datasets
  - voila
  - nbval
  - jupytext
  - selenium
  - scikit-image
  - tenacity
  - flaky